### ISSUE TITLE
Whoa...

### ISSUE THREAD

**Issue by noisybe** [kode54/Game_Music_Emu#13]
- 81 repositories
- all of them forks of projects that are still maintained and that are more up to date
- NO EMAIL

Looks like I found a hoarder.. ;D

Keep on doing... I was like that too once.. just make sure all these unfinished businesses are not on your mind all the time.. you know... you could just send patches and delegate the work to the original authors...

It is not like someone will love you for all these repositories...

**Comment by kode54** [comment]
How about you buzz off?
