### ISSUE TITLE
Could not replay Sangokushi 2 - Haou no Tairiku

### ISSUE THREAD

**Issue by wmjordan** [kode54/Game_Music_Emu#14]
I came from Droidsound, which used GME as one of its plugin.

The GME module could not replay the following NSFE file, which could be replayed with NotSoFatso on Windows with the following setting:

    Ignore Illegal=1

Is it possible to add support for this game music?

[Sangokushi 2 - Haou no Tairiku (EMU).zophar.zip](https://github.com/droidmjt/Droidsound/files/1998068/Sangokushi.2.-.Haou.no.Tairiku.EMU.zophar.zip)

**Comment by kode54** [comment]
That needs to be re-ripped. It should not be trying to execute opcodes which could have unpredictable effects. Stopping the core from executing undocumented opcodes which do have predictable, if unusual effects, is not as simple as inserting a switch into the player. And what if a rip actually requires these instructions to play?

**Comment by wmjordan** [comment]
Thank you for replying.

Very unfortunately, I don't know how to reach the ripper. And ripping an NSF is not so easy at all.
Enabling that music to be played, although theoretically could miss some "instructions", is still better than hearing nothing at all.

Furthermore, I have not encounter another file which requires that option. Only this one, and this one sound quite right on _NotSo Fatso_, with the `Ignore Illegal` option on.

That file has been on _Zophar_ for more than 10 years. Nobody else had provided another rip for that game. Maybe re-ripping that piece is a very tough task--much tougher than enabling the `Ignore Illegal` switch.

**Comment by wmjordan** [comment]
Someone has posted a fix for that NSF file here:
https://github.com/SourMesen/Mesen/issues/43

I applied the fix to the file and it was playable then.
[Sangokushi.2.-.Haou.no.Tairiku.EMU.zophar.zip](https://github.com/kode54/Game_Music_Emu/files/3032989/Sangokushi.2.-.Haou.no.Tairiku.EMU.zophar.zip)
