### ISSUE TITLE
[YM2151] huge differences between GME and foo_gep

### ISSUE THREAD

**Issue by R4to0** [kode54/Game_Music_Emu#15]
Hello Chris!

I've been messing with this library and a very small application to write wave files off from chiptune files. VGM YM2612 seems to work fine, however YM2151 tunes are playing strangely and sounding awful in comparsion to foo_gep foobar2000 component.

For comparison, I recorded samples on both GME library and foo_gep component (this one sounds right):
[sample_ym2151_gme.ogg](https://r4to0.azurewebsites.net/stuff/sample_ym2151_gme.ogg)
[sample_ym2151_foogep.ogg](https://r4to0.azurewebsites.net/stuff/sample_ym2151_foogep.ogg)

Original VGM file: [Circuit1.vgm](https://r4to0.azurewebsites.net/stuff/Circuit1.vgm)

It's strange since foo_gep is based on GME library and still sounds right. I have absolutely no clue why this happens! Does foo_gep uses a different library only for vgm?

I'm using your fork from your GitLab repository which seems the most up to date as I'm writing this.

Thanks for your help and thank you for all the libraries you maintain/develop for foobar2000!

**Comment by kode54** [comment]
I use VGMPlay in a library form for the VGM playback, which in turn is licensed GPL or worse, thanks to mixed source code origins. It lives in the `vgmplay` branch.

**Comment by R4to0** [comment]
Oh I'll see if I can get vmgplay brach to work on my application. Well, its just for fun and my own use so I don't think I'll get problems with GPL and if I even plan on releasing binaries to the public I'd prefer to share all the code as well.

Thanks a lot for the help.
