### ISSUE TITLE
Ym2608 has too loud sound

### ISSUE THREAD

**Issue by miralita** [kode54/Game_Music_Emu#5]
Hello!

I'm writing a Windows Phone 8 music player using your Game Music Emu library. Everything works fine except for the YM2608 is too loud for a VGM files (I tried PC-88 tracks from Zophar, like this one: http://www.zophar.net/music/s98/star-cruiser-[vgm]-pc-88-.html). Sound is clearly overloaded and distorted for almost all tracks.
I don't have knowledge about FM sound generation programming, so I couldn't fix it myself.
Could you please help me?

Thanks in advance!

**Comment by kode54** [comment]
Please use the vgmplay branch, as that contains the vgmplay library, and handles all formats supported by VGMPlay at this time.

**Comment by miralita** [comment]
Hello.

Yes, that helped. Thank you very much!
